// lib/sentiment.js
export function analyzeSentiment(message) {
  if (!message || typeof message !== "string") {
    return { label: "neutral", score: 0 };
  }

  const msg = message.toLowerCase();

  // Positive phrases and weights
  const positivePhrases = {
    "well maintained": 3,
    "very clean": 3,
    "helpful staff": 3,
    "supportive staff": 3,
    "friendly staff": 2,
    "prompt response": 2,
    "excellent service": 3,
    "great experience": 3,
    "comfortable environment": 2,
    "smooth process": 2,
    "productive session": 2,
    "highly recommended": 3,
    "efficient system": 2,
    "easy to access": 2,
    "safe environment": 2,
    "innovative solution": 2,
    "reliable staff": 2,
    "quick response": 2,
    "clean environment": 2,
    "quiet library": 3,
    "good canteen": 2,
    "helpful lecturer": 3,
    "smooth registration": 2,
    "well equipped lab": 2,
    "comfortable hostel": 2,
    "on-time lecture": 1,
    "accessible resources": 2,
    "successful exam": 2,
  };

  const positiveWords = {
    good: 1,
    great: 1,
    excellent: 2,
    amazing: 2,
    love: 2,
    happy: 1,
    wonderful: 2,
    fantastic: 2,
    awesome: 2,
    positive: 1,
    nice: 1,
    brilliant: 2,
    enjoy: 1,
    best: 2,
    helpful: 1,
    supportive: 1,
    friendly: 1,
    clean: 1,
    organized: 1,
    efficient: 1,
    prompt: 1,
    encouraging: 1,
    motivated: 1,
    accessible: 1,
    comfortable: 1,
    smooth: 1,
    improved: 2,
    satisfied: 1,
    successful: 1,
    productive: 1,
    creative: 1,
    innovative: 1,
    reliable: 1,
    inspiring: 2,
    enjoyable: 1,
    valuable: 1,
    convenient: 1,
    effective: 2,
    welcoming: 2,
    quiet: 2,
    "on-time": 1,
    "well-equipped": 2,
    easy: 1,
    efficient: 1,
    outstanding: 2,
    superb: 2,
    beautiful: 1,
    kind: 1,
    respectful: 1,
    polite: 1,
    cheerful: 1,
    joyful: 2,
    motivated: 2,
    thriving: 2,
    flourishing: 2,
    vibrant: 2,
    energetic: 2,
    powerful: 2,
    confident: 2,
    bold: 2,
    brave: 2,
    courageous: 2,
    determined: 2,
    persistent: 2,
    dedicated: 2,
    passionate: 2,
    enthusiastic: 2,
    supportive: 2,
    uplifting: 2,
    warm: 1,
    hospitable: 2,
    loving: 2,
    affectionate: 2,
    compassionate: 2,
    respectful: 2,
    pleasant: 2,
    delightful: 2,
    charming: 2,
    harmonious: 2,
    peaceful: 2,
    calm: 1,
    relaxed: 1,
    loyal: 2,
    dependable: 2,
    faithful: 2,
    devoted: 2,
    committed: 2,
    admired: 2,
    appreciated: 2,
    honored: 2,
    respected: 2,
    grateful: 2,
    thankful: 2,
    blessed: 2,
    lucky: 1,
    fortunate: 2,
    prosperous: 2,
    winner: 3,
    champion: 3,
    victorious: 3,
    triumphant: 3,
    achievement: 2,
    optimistic: 2,
    radiant: 2,
    shining: 1,
    brilliant: 2,
    dazzling: 2,
    excellent: 2,
    superb: 2,
    outstanding: 2,
    phenomenal: 3,
    remarkable: 2,
    spectacular: 2,
    extraordinary: 3,
    incredible: 2,
    terrific: 2,
    marvelous: 2,
    glorious: 2,
    majestic: 2,
    elegant: 2,
    graceful: 2,
    stylish: 1,
    classy: 1,
    wise: 2,
    clever: 2,
    intelligent: 2,
    genius: 3,
    creative: 2,
    imaginative: 2,
    resourceful: 2,
    innovative: 2,
    visionary: 2,
    diligent: 2,
    hardworking: 2,
    ambitious: 2,
    focused: 2,
    disciplined: 2,
    consistent: 2,
    resilient: 2,
    strong: 2,
    fearless: 2,
    unstoppable: 3,
    adaptable: 2,
    flexible: 2,
    patient: 1,
    caring: 2,
    nurturing: 2,
    kindhearted: 2,
    considerate: 2,
    thoughtful: 2,
    generous: 2,
    charitable: 2,
    selfless: 2,
    supportive: 2,
    cooperative: 2,
    collaborative: 2,
    united: 2,
    inclusive: 2,
    fair: 2,
    just: 2,
    equal: 2,
    humble: 2,
    modest: 2,
    genuine: 2,
    authentic: 2,
    trustworthy: 2,
    honest: 2,
    transparent: 2,
    honorable: 2,
    noble: 2,
    respectful: 2,
    forgiving: 2,
    merciful: 2,
    spiritual: 2,
    blessed: 2,
    blissful: 2,
    joyful: 2,
    cheerful: 2,
    bright: 2,
    sunny: 2,
    exciting: 2,
    fun: 1,
    adventurous: 2,
    playful: 2,
    lively: 2,
    festive: 2,
    celebratory: 2,
    proud: 2,
    accomplished: 2,
    capable: 2,
    skillful: 2,
    talented: 2,
    masterful: 2,
    expert: 2,
    professional: 2,
    accomplished: 2,
    efficient: 2,
    effective: 2,
    thriving: 2,
    growing: 2,
    advancing: 2,
    progressing: 2,
    improving: 2,
    developing: 2,
    successful: 2,
    victorious: 3,
    flourishing: 2,
    booming: 2,
    abundant: 2,
    rich: 2,
    wealthy: 2,
    thriving: 2,
    luxurious: 2,
    comfortable: 2,
    cozy: 1,
    safe: 2,
    secure: 2,
    stable: 2,
    strong: 2,
    reliable: 2,
    consistent: 2,
    uplifting: 2,
    motivating: 2,
    inspiring: 2,
    empowering: 2,
    transformative: 2,
    groundbreaking: 2,
    revolutionary: 2,
    legendary: 3,
    iconic: 2,
    timeless: 2,
    classic: 2,
    refreshing: 2,
    rejuvenating: 2,
    healing: 2,
    soothing: 2,
    relaxing: 1,
    calm: 1,
    balanced: 2,
    mindful: 2,
    wise: 2,
    enlightened: 2,
    awakened: 2,
    openminded: 2,
    tolerant: 2,
    patient: 2,
    peaceful: 2,
    harmonious: 2,
    connected: 2,
    united: 2,
    loyal: 2,
    devoted: 2,
    faithful: 2,
    eternal: 2,
    limitless: 2,
    infinite: 2,
    divine: 2,
    celestial: 2,
    heavenly: 2,
    miraculous: 3,
    magical: 2,
    enchanted: 2,
    wondrous: 2,
    joyful: 2,
    grateful: 2,
    thankful: 2,
    appreciative: 2,
    satisfied: 2,
    fulfilled: 2,
    content: 2,
    delighted: 2,
    pleased: 2,
    happy: 2,
    ecstatic: 3,
    euphoric: 3,
    blissful: 3,
  };

  // Negative phrases and weights
  const negativePhrases = {
    "poorly maintained": 3,
    "always noisy": 3,
    "staff is rude": 3,
    "staff unhelpful": 3,
    overcrowded: 2,
    "very crowded": 2,
    "extremely dirty": 3,
    "late response": 2,
    "hard to reach": 2,
    "inaccessible resources": 2,
    "confusing instructions": 2,
    "frustrating process": 2,
    "unorganized system": 2,
    "uncomfortable environment": 2,
    "poor service": 3,
    "bad experience": 3,
    "difficult to access": 2,
    "long wait": 2,
    disappointing: 2,
    "noisy library": 3,
    "dirty hostel": 3,
    "bad canteen": 2,
    "late lecture": 2,
    "unhelpful lecturer": 3,
    "exam stressful": 2,
    "poorly equipped lab": 2,
    "registration chaotic": 2,
    "crowded lecture hall": 2,
  };

   const negativeWords = {
     bad: 1,
     poor: 1,
     terrible: 2,
     hate: 2,
     sad: 1,
     angry: 1,
     horrible: 2,
     awful: 2,
     worst: 2,
     negative: 1,
     annoying: 1,
     boring: 1,
     disappoint: 2,
     problem: 1,
     noisy: 2,
     unhelpful: 1,
     crowded: 1,
     overcrowded: 2,
     dirty: 2,
     slow: 1,
     late: 1,
     confusing: 1,
     frustrating: 2,
     broken: 2,
     rude: 2,
     inefficient: 2,
     unorganized: 1,
     uncomfortable: 1,
     inaccessible: 2,
     unreliable: 2,
     stressful: 2,
     difficult: 1,
     messy: 1,
     unfair: 2,
     incomplete: 1,
     inconvenient: 1,
     unfriendly: 2,
     unacceptable: 2,
     unresponsive: 2,
     chaotic: 2,
     useless: 2,
     failure: 2,
     failed: 2,
     rejected: 2,
     hopeless: 2,
     helpless: 2,
     worthless: 2,
     meaningless: 2,
     unstable: 2,
     defeat: 2,
     cowardly: 2,
     foolish: 2,
     dumb: 2,
     stupid: 2,
     naive: 1,
     ridiculous: 2,
     nonsense: 2,
     absurd: 2,
     pathetic: 2,
     clumsy: 1,
     ignorant: 2,
     betrayal: 2,
     dishonest: 2,
     corruption: 2,
     scam: 2,
     fraud: 2,
     violent: 3,
     abusive: 3,
     bullying: 3,
     hatred: 3,
     oppression: 2,
     injustice: 2,
     discrimination: 2,
     prejudice: 2,
     biased: 2,
     harmful: 2,
     dangerous: 3,
     threat: 3,
     destructive: 2,
     ruined: 2,
     collapsed: 2,
     bankrupt: 2,
     loss: 2,
     wasted: 2,
     futile: 2,
     pointless: 2,
     toxic: 2,
     miserable: 2,
     suffering: 2,
     careless: 1,
     lazy: 1,
     arrogant: 2,
     hostile: 2,
     weak: 1,
     fragile: 1,
     reckless: 2,
     negligent: 2,
     exploit: 2,
     exploitative: 2,
     manipulative: 2,
     selfish: 2,
     greedy: 2,
     insult: 2,
     insulting: 2,
     shame: 2,
     ashamed: 2,
     guilty: 2,
     jealousy: 2,
     envious: 2,
     envy: 2,
     bitter: 2,
     cruelty: 2,
     cruel: 2,
     chaos: 2,
     incapable: 2,
     disloyal: 2,
     distrust: 2,
     suspicious: 1,
     neglect: 2,
     neglected: 2,
     inadequate: 2,
     incompetent: 2,
     tragedy: 2,
     tragic: 2,
     sorrow: 2,
     grief: 2,
     depressed: 2,
     depression: 2,
     anxiety: 2,
     anxious: 2,
     panic: 2,
     nervous: 1,
     tense: 1,
     overwhelmed: 2,
     exhausted: 1,
     burnout: 2,
     sick: 1,
     illness: 2,
     disease: 2,
     pain: 2,
     hurt: 2,
     injured: 2,
     accident: 2,
     disaster: 3,
     catastrophe: 3,
     crisis: 3,
     collapse: 2,
     poverty: 2,
     hunger: 2,
     starving: 2,
     weakling: 1,
     ineffective: 2,
     underwhelming: 2,
     mediocre: 2,
     inferior: 2,
     obsolete: 2,
     outdated: 2,
     malfunction: 2,
     glitch: 1,
     bug: 1,
     failing: 2,
     error: 1,
     corrupt: 2,
     hopelessness: 2,
     lost: 2,
     doomed: 2,
     pointless: 2,
     vain: 1,
     terrible: 2,
     disgusting: 3,
     gross: 2,
     nasty: 2,
     vulgar: 2,
     offensive: 2,
     insulting: 2,
     degrading: 2,
     humiliating: 2,
     disrespectful: 2,
     inconsiderate: 2,
     selfishness: 2,
     greed: 2,
     spiteful: 2,
     vengeful: 2,
     resentful: 2,
     bitterly: 2,
     pessimistic: 2,
     negative: 2,
     gloomy: 2,
     bleak: 2,
     dark: 1,
     hopelessly: 2,
     awful: 2,
     shameful: 2,
     pitiful: 2,
     tragic: 2,
     harsh: 2,
     brutal: 3,
     savage: 3,
     evil: 3,
     monstrous: 3,
     villainous: 3,
     horrific: 3,
     nightmarish: 3,
     dreadful: 3,
     frightful: 3,
     alarming: 2,
     appalling: 3,
     atrocious: 3,
     abysmal: 3,
     horrendous: 3,
     dire: 2,
     wretched: 3,
     vile: 3,
     foul: 3,
     repulsive: 3,
     revolting: 3,
     hideous: 3,
     grotesque: 3,
     sickening: 3,
     poisonous: 3,
     lethal: 3,
     hazardous: 3,
     unsafe: 3,
     insecure: 2,
     unstable: 2,
     shaky: 1,
     flimsy: 1,
     brokenness: 2,
     ruin: 2,
     devastation: 3,
     collapse: 2,
     destruction: 3,
     annihilation: 3,
     chaos: 2,
     mayhem: 2,
     disorder: 2,
     turmoil: 2,
     unrest: 2,
     riot: 3,
     violence: 3,
     aggression: 3,
     hostility: 2,
     war: 3,
     conflict: 2,
     fight: 2,
     quarrel: 2,
     argument: 1,
     dispute: 1,
     confrontation: 2,
     tension: 2,
     stress: 2,
     frustration: 2,
     irritation: 1,
     annoyance: 1,
     anger: 2,
     rage: 3,
     fury: 3,
     wrath: 3,
     outrage: 2,
     resentment: 2,
     bitterness: 2,
     hatred: 3,
     loathing: 3,
     disgust: 3,
     abhorrence: 3,
     contempt: 3,
     scorn: 2,
     disrespect: 2,
     mockery: 2,
     ridicule: 2,
     insult: 2,
     offense: 2,
     slander: 2,
     defamation: 2,
     humiliation: 2,
     embarrassment: 2,
     shame: 2,
     guilt: 2,
     regret: 2,
     remorse: 2,
     sorrowful: 2,
     grief: 2,
     despair: 2,
     anguish: 2,
     agony: 2,
     torment: 2,
     suffering: 2,
     misery: 2,
     sadness: 2,
     loneliness: 2,
     isolation: 2,
     alienation: 2,
     rejection: 2,
     neglect: 2,
     abandonment: 2,
     betrayal: 2,
     treachery: 2,
     deceit: 2,
     deception: 2,
     dishonesty: 2,
     lie: 1,
     cheating: 2,
     fraud: 2,
     scam: 2,
     corruption: 2,
     bribery: 2,
     manipulation: 2,
     exploitation: 2,
     oppression: 2,
     persecution: 2,
     abuse: 2,
     violence: 3,
     crime: 2,
     murder: 3,
     killing: 3,
     assault: 3,
     theft: 2,
     robbery: 2,
     burglary: 2,
     vandalism: 2,
     destruction: 3,
     terrorism: 3,
     threat: 3,
     danger: 3,
     hazard: 3,
     risk: 2,
     failure: 2,
   };


  const negations = [
    "not",
    "never",
    "no",
    "none",
    "cannot",
    "can't",
    "hardly",
    "rarely",
    "never ever",
    "not very",
    "not at all",
  ];

  let score = 0;

  // Multi-word phrase handling
  Object.entries(positivePhrases).forEach(([phrase, weight]) => {
    if (msg.includes(phrase)) score += weight;
  });

  Object.entries(negativePhrases).forEach(([phrase, weight]) => {
    if (msg.includes(phrase)) score -= weight;
  });

  const words = msg.split(/\s+/);
  let negationActive = false;

  for (let i = 0; i < words.length; i++) {
    let word = words[i];

    for (let neg of negations.sort(
      (a, b) => b.split(" ").length - a.split(" ").length
    )) {
      const negWords = neg.split(" ");
      const segment = words.slice(i, i + negWords.length).join(" ");
      if (segment === neg) {
        negationActive = true;
        i += negWords.length - 1;
        break;
      }
    }

    if (positiveWords[word]) {
      score += negationActive ? -positiveWords[word] : positiveWords[word];
      negationActive = false;
      continue;
    }

    if (negativeWords[word]) {
      score += negationActive ? negativeWords[word] : -negativeWords[word];
      negationActive = false;
      continue;
    }

    negationActive = false;
  }

  let label = "neutral";
  if (score > 1) label = "positive";
  else if (score < -1) label = "negative";

  return { label, score };
}
